feat: support ignoring mapping in help panel
sindrets/diffview.nvim pull request #278
Opened 2022-12-30 04:25 UTC by fjchen7

2022-12-30 11:07 UTC, sindrets commented
@fjchen7 Thanks for the PR!

I'm missing some explanation for this change. What's the point of hiding entries from the help panel?

2022-12-30 12:09 UTC, fjchen7 commented
The final purpose is to make help  panel cleaner if user wants.

For me the specific requirement is:

```lua
require("diffview").setup {
  view = {
    file_panel = {
      -- I don't want to show some conventional keymaps
      { "n", "j", actions.next_entry, { desc = false } },
      { "n", "<down>", actions.next_entry, { desc = false } },
      { "n", "k", actions.prev_entry, { desc = false } },
      { "n", "<up>", actions.prev_entry, { desc = false } },

      -- I want to disable some keymaps withouts showing them in help panel.
      { "n", "<C-o>", "", { desc = false } },  -- Avoid accidentally messing up buffer
      { "n", "<C-i>", "", { desc = false } },
    }
  }
}
```

2023-01-03 13:35 UTC, sindrets commented on lua/diffview/ui/panels/help_panel.lua
> +      if comp.context.label_rhs == "diffview_ignored" then goto continue end
Don't use `goto` here. Just use normal branching:

```
if comp.context.label_rhs ~= "diffview_ignored" then --[[ ... ]]
```

2023-01-03 14:10 UTC, sindrets requested changes
Setting the `desc` field to anything other than a string is unintended usage of the `nvim_set_keymap()` API. While it seems to have no side effects right now; there's no guarantee it will stay that way in the future. We need to do this properly and special-case this behavior in the plugin's keymap processing.

You can check [here](https://github.com/sindrets/diffview.nvim/blob/e3e15d8f1d727056185fc1696be1554837dec897/lua/diffview/config.lua#L403-L411) whether the `desc` field has been set to `false`, and if so, change the value of the expanded mapping to `__DIFFVIEW_IGNORED__` or something.

2023-01-05 03:55 UTC, fjchen7 commented
Of we directly choose the special string like `__DIFFVIEW_IGNORED__` or something to hide keymap? (Just like `which_key_ignore` in [which-key](https://github.com/folke/which-key.nvim)) For example,

```lua
{ "n", "<2-LeftMouse>", actions.select_entry, { desc = "__DIFFVIEW_IGNORED__" } },
```

In my opinion, this could avoid conflict with the extension about `desc = false` in `nvim_set_keymap()` and may be better.

2023-01-05 13:05 UTC, sindrets commented
@fjchen7 good call. Let's just go with `"diffview_ignore"` as the special value then.

2023-01-08 12:47 UTC, sindrets approved these changes
Thanks!

2023-01-08 12:49 UTC, merged