fix: Fix version check for mercurial
sindrets/diffview.nvim pull request #364
Opened 2023-05-30 15:57 UTC by Pagliacii

Close #363

2023-05-30 16:58 UTC, sindrets commented
Thanks for the PR! This is indeed a bug. But there has to be a better way to validate this without all the redundant statements. How about something like this:

```lua
local version_ok = (function()
  if v.major ~= target.major then
    return v.major > target.major
  elseif v.minor ~= target.minor then
    return v.minor > target.minor
  elseif v.patch ~= target.patch then
    return v.patch > target.patch
  end
  return true
end)()
```

2023-05-30 17:05 UTC, Pagliacii commented
Updated

2023-05-30 17:15 UTC, sindrets commented on lua/diffview/vcs/adapters/hg/init.lua
> +  bs.version_string = out[1] and out[1]:match("Mercurial .*%(version (%d%.%d%.%d).*%)") or nil
This pattern won't match version numbers composed of more than a single digit.

```suggestion
  bs.version_string = out[1] and out[1]:match("Mercurial .*%(version (%d+%.%d+%.%d+)+%S*%)") or nil
```

2023-05-30 17:19 UTC, sindrets reviewed
Could you please also apply the same fix to the git adapter?

https://github.com/sindrets/diffview.nvim/blob/bff58a6ea3e081ca50049700f9848b2f84ea57be/lua/diffview/vcs/adapters/git/init.lua#L100

2023-05-31 01:34 UTC, Pagliacii commented
Sure, I will check it at tonight.

2023-05-31 14:41 UTC, Pagliacii commented
Updated.

Today I found that the mercurial has version likes this:

```text
Mercurial Distributed SCM (version 6.4)
(see https://mercurial-scm.org for more information)

Copyright (C) 2005-2023 Olivia Mackall and others
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

So I use the `hg_version` function to extract version info from cli output. And move the **version checker** to `vcs.utils`.

2023-05-31 16:06 UTC, sindrets requested changes

2023-06-01 14:02 UTC, Pagliacii commented on lua/diffview/vcs/adapters/hg/init.lua
> +  end
You're right.

2023-06-01 14:20 UTC, Pagliacii commented on lua/diffview/vcs/adapters/hg/init.lua
> +  end
Updated

2023-06-01 15:39 UTC, sindrets approved these changes
LGTM, thank you!

2023-06-01 15:39 UTC, merged

2023-06-02 06:22 UTC, zegervdv commented
@Pagliacii thanks for fixing this!
I ran into it one day, but didn't have time to debug it. The next day it was gone, so probably my version got updated in the meantime :).

Nice to see someone else is using it with mercurial.