git log: new flags before & after
sindrets/diffview.nvim pull request #370
Opened 2023-06-05 18:23 UTC by emmanueltouzery

support for git log flags.

2023-06-06 11:25 UTC, sindrets requested changes
Thanks for the PR! This looks pretty good. Please just amend [the type definition for `GitLogOptions`](https://github.com/emmanueltouzery/diffview.nvim/blob/df507ddea4f064f1a750f429230ebe373ba196fe/lua/diffview/config.lua#L254) and the docs for `:h :DiffviewFileHistory`.

2023-06-06 11:34 UTC, sindrets commented
In the docs it could also be worth mentioning that the flags accept dates in natural language as well (like i.e. `"2 weeks 6 hours 12 minutes ago"`).

2023-06-06 11:35 UTC, sindrets commented on lua/diffview/vcs/adapters/git/init.lua
> +    FlagOption("=A", "--after==", "List only commits after a certain date", {
Should only be one equal sign: `--after=`

2023-06-06 19:40 UTC, emmanueltouzery commented
applied the requested changes :+1:

2023-06-07 10:35 UTC, sindrets approved these changes
LGTM, thank you! I made a small change adding Git's synonyms for these flags `--since` and `--until`.

2023-06-07 10:36 UTC, emmanueltouzery commented
:+1: on the since & until.

2023-06-07 10:38 UTC, merged