feat: File tree
sindrets/diffview.nvim pull request #73
Opened 2021-09-13 18:45 UTC by farbodsz

Hello,

Following on from our conversation earlier, I've been working on the file tree view.

It's not finished, but I'll open this PR in case you have any feedback at this stage.

The next main step is constraining cursor position to disable selection of directory names. After this it's just a matter of making the file tree view an option and adding documentation.

2021-09-18 23:01 UTC, sindrets requested changes
Thank you for working on this! You are on the right track here, but there are some implementation details that need some attention.

Like I mentioned: I might open a PR to your branch to address some of the implementation details, because they implicate involving several systems that are not exactly well documented, and I want to spare you the headache of deciphering undocumented code.

2021-09-18 23:16 UTC, farbodsz commented
Thanks so much for the detailed feedback @sindrets .

I've spent some time last week looking at the render component system and how it might work with the file tree but didn't have much time to actually start implementing it properly. My plan is to work more on the file tree this week since I'll have more time from Monday onwards.

You made a lot of useful suggestions too so I'd like to go over them this week and can let you know if I have any questions along the way.

2021-09-19 14:25 UTC, farbodsz commented on lua/diffview/views/file_tree/node.lua
> +function Node:children_recursive(start_depth)
This is true - I've realised this when testing my changes too and is something I'm planning to fix.

2021-09-22 15:52 UTC, farbodsz commented
@sindrets Oh I'm sorry I didn't see your pull request! (I was never notified of it)

Will take a look at it now and merge in your work.

Thanks!

2021-09-22 17:48 UTC, farbodsz commented
Ok the commit history looks a bit convoluted after the merge but it should be fine since we're squash merging this branch anyway.

Basically all the things I was going to add in this PR are things you also mentioned in your PR description, which is great. I'll put them here too for completeness (and in this PR's description).

- Documentation
- Git status for folders
- Compacting empty folders to preserve horizontal space (see the similar feature I implemented in nvim-tree: feat: Option for grouping empty directories kyazdani42/nvim-tree.lua#247)

2021-09-22 22:09 UTC, farbodsz commented
Hey @sindrets 

I've merged in your changes and added git statuses for directories. I would like to add some configurable options for this, something like:

```lua
require("diffview").setup({
  ...

  file_panel = {
    ...
    listing_style = "tree",
    directory_statuses = "always"  -- One of 'never', 'only_folded' or 'always'
  },
  ...
}
```

What are your thoughts on this?

The other thing I wanted to ask you, is what you mean by "proper highlight groups" in a todo comment in `render.lua`:

```lua
local function render_file_tree_recurse(depth, comp)
  -- TODO: Proper highlight groups
  local conf = config.get_config()
  ...
```

It seems to me that the correct highlighting for directories is already implemented there, so I was wondering if this a todo comment from before highlighting was added, or whether you're thinking of adding some other highlighting?

2021-09-23 15:13 UTC, sindrets commented
> I've [...] added git statuses for directories. I would like to add some configurable options for this [...]

@farbodsz  I like this idea! The options you suggested seem good, with `always` being the default.

> The other thing I wanted to ask you, is what you mean by "proper highlight groups" in a todo comment

It's preferable to use custom highlight groups, because this lets users and theme creators customize the look of the plugin without having to change basic highlight groups that are used for many other things. Take a look in `diffview/colors.lua`. We should at least add these groups:
- `DiffviewFolderName`: links to `Directory`
- `DiffviewFolderIcon`: links to `PreProc`

You can change the fold sign to use the `DiffviewNonText` group.

Also: could you make `flatten_dirs` enabled by default? Pretty much any project with any complexity to its directory structure is practically always gonna have a bunch of compactable folders for any revision.

2021-09-23 18:12 UTC, farbodsz commented
Ok all done!

But before we merge, I was wondering something - in config options we have something like:

```lua 
  ...
  signs = {
    ...
    folder_closed = "-",
    folder_open = "-",
  },
```

and I assume this is so that the user can set folder icons, like how we use devicons on the files.

But if the user doesn't use devicons, then a sign next to the folder is still shown. Like this:

![screenshot_20210923_190649](https://user-images.githubusercontent.com/12140044/134560600-9a230092-5b05-4be1-8089-f1c93e803786.png)

Having folder icons without using file devicons looks a little strange, and even if I set `folder_{closed|open}` to `""` then there's still an additional whitespace character:

![screenshot_20210923_190946](https://user-images.githubusercontent.com/12140044/134560958-19c3d9bb-7d00-4e7f-a949-27b69008866b.png)

It would be easy to make folder icons optional in one of the following ways:

1. Check if devicons is enabled. If so, use the folder signs in the config.
2. Only use the folder signs in the config if not empty/nil.
3. Additional option like `use_folder_signs` (I'm not a fan of this one)

What do you think?

2021-09-23 18:23 UTC, sindrets commented
Here's what I think we should do:
- Move `folder_close`, `folder_open` to a new config key `icons`
  - It would be strange if there were inconsistencies between the conditions for when we use the symbols from `signs`. And I want people to be able to configure folds without enabling icons.
- Only use these if user has `use_icons` enabled.

2021-09-23 18:26 UTC, farbodsz commented
@sindrets yep that sounds good to me. I'll make the changes now.

2021-09-23 20:05 UTC, sindrets approved these changes
Brilliant. Fantastic work. Many thanks!

I'll merge this as is because it works very well, but here are some TODO's for the future:
- Make `toggle_stage_entry` work on folders in the tree.
- Fold mappings in the tree.
- Indent guides. 
  - I personally really like indent guides in trees because it makes them so much easier to read in my opinion.

These are not high priority and I can take care of them later.

Again: many thanks for your work!

2021-09-23 20:13 UTC, merged